name: Update Trends
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run update script
        run: python scripts/update.py
      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "data: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
      - name: Publish data to docs
        run: |
          mkdir -p docs/data
          cp -a data/* docs/data/
          touch docs/.nojekyll
          git add docs/data docs/.nojekyll
          git commit -m "pages: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
